# Generated by Django 5.1.4 on 2024-12-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandarshan_userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('access_expiry', models.DateTimeField()),
                ('office_location', models.CharField(max_length=100)),
                ('room_access', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('reason_for_visit', models.TextField()),
                ('access_expiry', models.DateTimeField()),
                ('office_location', models.CharField(max_length=100)),
                ('room_access', models.TextField()),
            ],
        ),
    ]
